apiVersion: v1
kind: Namespace
metadata:
  name: '$app'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: '$app'
  namespace: '$app'
  labels:
    app: '$app'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '$app'
  template:
    metadata:
      name: '$app'
      labels:
        app: '$app'
        build: $tag
    spec:
      containers:
      - name: '$app'
        image: '$dockerRegistry:$tag'
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: '$app'
  namespace: '$app'
  labels:
    app: '$app'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
  selector:
    app: '$app'
