apiVersion: v1
kind: Service
metadata:
  name: chuck
  labels:
    name: chuck
spec:
  # clusterIP: 10.0.0.10
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: chuck
    version: 0.1.0